#!/usr/bin/env python3
"""Regenerate src/data/mediaSizes.ts from whatever is in public/images.

Run after adding or replacing any image so components keep reserving the
right amount of space before an asset loads (no cumulative layout shift).
"""
import glob, os
from PIL import Image

Image.MAX_IMAGE_PIXELS = None
ROOT = os.path.join(os.path.dirname(__file__), "..")
PUB = os.path.join(ROOT, "public")

rows = []
for f in sorted(glob.glob(f"{PUB}/images/**/*.*", recursive=True)):
    if not f.lower().endswith((".webp", ".png", ".jpg", ".jpeg")):
        continue
    with Image.open(f) as im:
        w, h = im.size
    rows.append(f"  \"/{os.path.relpath(f, PUB)}\": [{w}, {h}],")

with open(os.path.join(ROOT, "src/data/mediaSizes.ts"), "w") as fh:
    fh.write("/* Generated by scripts/gen-media-sizes.py — do not edit by hand.\n")
    fh.write("   Intrinsic [width, height] for every asset, so images and videos\n")
    fh.write("   reserve their space before loading. */\n\n")
    fh.write("export const mediaSizes: Record<string, [number, number]> = {\n")
    fh.write("\n".join(rows))
    fh.write("\n};\n")

print(f"mediaSizes.ts — {len(rows)} entries")
